import type { ReactNode } from 'react';
import { useSiteConfig } from '../site';
import { useLang, useT } from '../i18n';
import { isPortal } from '../platform';

function Page({ title, onBack, children }: { title: string; onBack: () => void; children: ReactNode }) {
  const t = useT();
  return (
    <div className="home legal">
      <header className="home-header">
        <button className="btn ghost" onClick={onBack}>
          ← {t('Lobby', 'Lobby')}
        </button>
        <h1 className="page-title">{title}</h1>
        <span />
      </header>
      <article className="card legal-body">{children}</article>
    </div>
  );
}

function PrivacyEn({ onBack }: { onBack: () => void }) {
  const cfg = useSiteConfig();
  return (
    <Page title="Privacy policy" onBack={onBack}>
      <p className="muted">Last updated: October 2026</p>
      <h2>Who runs this site</h2>
      <p>
        The data controller is {cfg.owner || 'the operator of Metropoly'}
        {cfg.contactEmail && (
          <>
            , reachable at <a href={`mailto:${cfg.contactEmail}`}>{cfg.contactEmail}</a>
          </>
        )}
        .
      </p>
      <h2>What data we use</h2>
      <ul>
        <li>
          <b>The nickname, token and color</b> you choose, to show you to the other players.
        </li>
        <li>
          <b>Chat messages</b>, sent to the players in your room and kept in memory only while the room exists.
        </li>
        <li>
          <b>An anonymous identifier</b> generated by your browser, so you can rejoin a game after losing the connection.
        </li>
        <li>
          <b>Technical data</b> (IP address, browser type) processed by the hosting provider to run the service and for security.
        </li>
      </ul>
      <p>We don’t ask for emails, real names or payment details and we don’t build advertising profiles.</p>
      <h2>Data stored on your device</h2>
      <p>
        We use your browser’s <i>local storage</i> (no tracking cookies) to remember your profile, settings, sound preference and the boards you
        create. You can delete it at any time from your browser settings.
      </p>
      <h2>Game portals</h2>
      <p>If you play Metropoly inside a game portal (such as CrazyGames or Poki), the portal may show ads and use cookies under its own privacy policy.</p>
      <h2>Retention</h2>
      <p>Games and chats are not stored permanently: they disappear when the room closes or the server restarts.</p>
      <h2>Your rights</h2>
      <p>You can ask for access to, or deletion of, your data by contacting the data controller, and you can lodge a complaint with your data protection authority.</p>
    </Page>
  );
}

export function Privacy({ onBack }: { onBack: () => void }) {
  const lang = useLang();
  return lang === 'en' ? <PrivacyEn onBack={onBack} /> : <PrivacyIt onBack={onBack} />;
}

function PrivacyIt({ onBack }: { onBack: () => void }) {
  const cfg = useSiteConfig();
  const who = cfg.owner || 'il gestore di Metropoly';
  return (
    <Page title="Privacy" onBack={onBack}>
      <p className="muted">Ultimo aggiornamento: ottobre 2026</p>
      <h2>Chi gestisce il sito</h2>
      <p>
        Il titolare del trattamento è {who}
        {cfg.contactEmail && (
          <>
            , contattabile all’indirizzo <a href={`mailto:${cfg.contactEmail}`}>{cfg.contactEmail}</a>
          </>
        )}
        .
      </p>
      <h2>Quali dati usiamo</h2>
      <ul>
        <li>
          <b>Nickname, pedina e colore</b> che scegli: servono per mostrarti agli altri giocatori durante la partita.
        </li>
        <li>
          <b>Messaggi di chat</b>: vengono inviati agli altri giocatori della stanza e restano in memoria solo finché la stanza esiste.
        </li>
        <li>
          <b>Un identificativo anonimo</b> generato dal tuo browser, per farti rientrare nella partita se perdi la connessione.
        </li>
        <li>
          <b>Dati tecnici</b> (indirizzo IP, tipo di browser) trattati dal fornitore di hosting per far funzionare il servizio e per sicurezza.
        </li>
      </ul>
      <p>Non chiediamo email, nomi reali o dati di pagamento e non creiamo profili pubblicitari.</p>
      <h2>Dati salvati sul tuo dispositivo</h2>
      <p>
        Usiamo il <i>local storage</i> del browser (non cookie di tracciamento) per ricordare il tuo profilo, le impostazioni, i suoni e i tabelloni
        che crei. Puoi cancellarli in qualsiasi momento dalle impostazioni del browser.
      </p>
      <h2>Portali di giochi</h2>
      <p>
        Se giochi a Metropoly dentro un portale (come CrazyGames o Poki), il portale può mostrare pubblicità e usare cookie secondo la propria
        informativa privacy, che ti invitiamo a leggere.
      </p>
      <h2>Per quanto tempo</h2>
      <p>Le partite e le chat non vengono salvate in modo permanente: spariscono quando la stanza viene chiusa o il server si riavvia.</p>
      <h2>I tuoi diritti</h2>
      <p>
        Puoi chiedere accesso, cancellazione o informazioni sui tuoi dati scrivendo al titolare. Hai anche il diritto di presentare reclamo al
        Garante per la protezione dei dati personali.
      </p>
      <h2>Minori</h2>
      <p>Il gioco è adatto a tutti; non raccogliamo consapevolmente dati personali dei minori oltre a quanto descritto sopra.</p>
    </Page>
  );
}

function TermsEn({ onBack }: { onBack: () => void }) {
  return (
    <Page title="Terms of use" onBack={onBack}>
      <p className="muted">Last updated: October 2026</p>
      <h2>The service</h2>
      <p>
        Metropoly is a free property trading game you can play online with other people or against the computer. It is an independent game, not
        affiliated with or endorsed by any board game publisher. In-game money is virtual and has no real value.
      </p>
      <h2>Behaviour</h2>
      <ul>
        <li>Be respectful: no insults, offensive content, spam or inappropriate nicknames in chat, names or shared boards.</li>
        <li>Don’t try to tamper with the game, the server or other people’s games.</li>
        <li>The host of a room can remove participants before the game starts.</li>
      </ul>
      <h2>Custom boards</h2>
      <p>You are responsible for the texts you put on your boards and the links you share. Don’t use other people’s trademarks, names or content without permission.</p>
      <h2>Availability</h2>
      <p>The service is provided “as is”: it may be interrupted, changed or restarted at any time, possibly losing games in progress.</p>
    </Page>
  );
}

export function Terms({ onBack }: { onBack: () => void }) {
  const lang = useLang();
  return lang === 'en' ? <TermsEn onBack={onBack} /> : <TermsIt onBack={onBack} />;
}

function TermsIt({ onBack }: { onBack: () => void }) {
  return (
    <Page title="Termini di utilizzo" onBack={onBack}>
      <p className="muted">Ultimo aggiornamento: ottobre 2026</p>
      <h2>Il servizio</h2>
      <p>
        Metropoly è un gioco gratuito di compravendita di proprietà, giocabile online con altre persone o contro il computer. È un gioco indipendente,
        non affiliato né approvato da alcun produttore di giochi da tavolo. Il denaro del gioco è virtuale e non ha alcun valore reale.
      </p>
      <h2>Comportamento</h2>
      <ul>
        <li>Sii rispettoso: niente insulti, contenuti offensivi, spam o nickname inappropriati in chat, nei nomi o nei tabelloni condivisi.</li>
        <li>Non provare a manomettere il gioco, il server o le partite degli altri.</li>
        <li>L’host di una stanza può rimuovere i partecipanti prima dell’inizio della partita.</li>
      </ul>
      <h2>Tabelloni personalizzati</h2>
      <p>
        Sei responsabile dei testi che inserisci nei tuoi tabelloni e nei link che condividi. Non usare marchi, nomi o contenuti di altri senza averne
        il diritto.
      </p>
      <h2>Disponibilità</h2>
      <p>
        Il servizio è offerto “così com’è”: può essere interrotto, modificato o riavviato in qualsiasi momento, con la possibile perdita delle partite
        in corso.
      </p>
      <h2>Contributi volontari</h2>
      <p>
        Eventuali donazioni o acquisti di contenuti estetici sono volontari e servono a sostenere lo sviluppo. Non danno vantaggi nelle partite.
      </p>
    </Page>
  );
}

export function Footer({ onNav }: { onNav: (route: string) => void }) {
  const cfg = useSiteConfig();
  const t = useT();
  return (
    <footer className="site-footer">
      <nav>
        {/* Game portals don't allow links to external sites. */}
        {!isPortal && cfg.supportUrl && (
          <a href={cfg.supportUrl} target="_blank" rel="noopener noreferrer">
            ❤️ {t('Supporta Metropoly', 'Support Metropoly')}
          </a>
        )}
        <button onClick={() => onNav('/editor')}>🎨 {t('Tabelloni', 'Boards')}</button>
        {!isPortal && (
          <a href={cfg.issuesUrl} target="_blank" rel="noopener noreferrer">
            🐞 {t('Segnala un problema', 'Report a problem')}
          </a>
        )}
        <button onClick={() => onNav('/privacy')}>Privacy</button>
        <button onClick={() => onNav('/termini')}>{t('Termini', 'Terms')}</button>
      </nav>
      <small className="muted">
        {t(
          'Metropoly è un gioco indipendente, non affiliato ad alcun marchio di giochi da tavolo.',
          'Metropoly is an independent game, not affiliated with any board game brand.',
        )}
      </small>
    </footer>
  );
}
